// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeacherControl.DAL;

namespace TeacherControl.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200509005855_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("TeacherControl.Models.Adicionales", b =>
                {
                    b.Property<int>("AdicionalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<float>("Puntos")
                        .HasColumnType("REAL");

                    b.HasKey("AdicionalId");

                    b.ToTable("Adicionales");
                });

            modelBuilder.Entity("TeacherControl.Models.Estudiantes", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NacionalidadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Semestre")
                        .HasColumnType("INTEGER");

                    b.HasKey("EstudianteId");

                    b.HasIndex("NacionalidadId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("TeacherControl.Models.Nacionalidades", b =>
                {
                    b.Property<int>("NacionalidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("TEXT");

                    b.HasKey("NacionalidadId");

                    b.ToTable("Nacionalidades");

                    b.HasData(
                        new
                        {
                            NacionalidadId = 1,
                            Nacionalidad = "Dominicana"
                        });
                });

            modelBuilder.Entity("TeacherControl.Models.Tareas", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<float>("Puntos")
                        .HasColumnType("REAL");

                    b.HasKey("TareaId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("TeacherControl.Models.TareasDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requerimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("TareaId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TareaId");

                    b.ToTable("TareasDetalle");
                });

            modelBuilder.Entity("TeacherControl.Models.Estudiantes", b =>
                {
                    b.HasOne("TeacherControl.Models.Nacionalidades", "Nacionalidad")
                        .WithMany()
                        .HasForeignKey("NacionalidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeacherControl.Models.TareasDetalle", b =>
                {
                    b.HasOne("TeacherControl.Models.Tareas", null)
                        .WithMany("Detalle")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
